-- Supabase Complete Schema - Firebase %100 Compatible
-- Tüm field adları Firebase export'undan çıkarıldı
-- PostgreSQL case-sensitive için tırnak içinde

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. CLUBS
CREATE TABLE clubs (
    id TEXT PRIMARY KEY,
    name TEXT,
    icon TEXT,
    city TEXT,
    phone TEXT,
    description TEXT,
    status TEXT,
    active BOOLEAN,
    "adminEmail" TEXT,
    "adminName" TEXT,
    "adminPhone" TEXT,
    "memberCount" INTEGER,
    "crmEnabled" BOOLEAN,
    "productCategories" JSONB,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT,
    "updatedAt" TIMESTAMPTZ,
    "updatedBy" TEXT
);

-- 2. USERS
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT,
    username TEXT,
    password TEXT,
    role TEXT,
    "clubId" TEXT,
    "clubName" TEXT,
    "fullName" TEXT,
    phone TEXT,
    "phoneNumber" TEXT,
    permissions JSONB,
    "isSuperAdmin" BOOLEAN,
    "notificationPermission" TEXT,
    "notificationPermissionAsked" BOOLEAN,
    "notificationPermissionDate" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT,
    "updatedAt" TIMESTAMPTZ
);

-- 3. MEMBERS
CREATE TABLE members (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "Ad_Soyad" TEXT,
    "Resit_Olmayan_Adi_Soyadi" TEXT,
    "Telefon" TEXT,
    "Telefon_2" TEXT,
    "Email" TEXT,
    "TC_No" TEXT,
    "TC_Kimlik_No" TEXT,
    "Dogum_Tarihi" TIMESTAMPTZ,
    "Brans" TEXT,
    "Uyelik_Baslangic_Tarihi" TIMESTAMPTZ,
    "Adres" TEXT,
    "Veli_2_Adi_Soyadi" TEXT,
    status TEXT,
    "memberType" TEXT,
    "preRegistrationId" TEXT,
    signature TEXT,
    "contractDate" TIMESTAMPTZ,
    "registrationDate" TIMESTAMPTZ,
    "studentBirthDate" TIMESTAMPTZ,
    "completedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ
);

-- 4. PRE-REGISTRATIONS
CREATE TABLE "preRegistrations" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "Ad_Soyad" TEXT,
    "Ogrenci_Ad_Soyad" TEXT,
    "Telefon" TEXT,
    phone TEXT,
    phone2 TEXT,
    "Email" TEXT,
    "TC_No" TEXT,
    "TC_Kimlik_No" TEXT,
    "Dogum_Tarihi" TIMESTAMPTZ,
    branch TEXT,
    "Adres" TEXT,
    address TEXT,
    status TEXT,
    "memberType" TEXT,
    signature TEXT,
    "contractDate" TIMESTAMPTZ,
    "contractPdf" TEXT,
    "studentName" TEXT,
    "studentBirthDate" TIMESTAMPTZ,
    "parentName" TEXT,
    "parentName2" TEXT,
    "parentBirthDate" TIMESTAMPTZ,
    "parentTc" TEXT,
    "monthlyFee" DECIMAL(10,2),
    "paymentDay" INTEGER,
    "paymentSchedule" JSONB,
    "periodStart" DATE,
    "periodEnd" DATE,
    notes TEXT,
    "completedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ
);

-- 5. GROUPS
CREATE TABLE groups (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    name TEXT,
    "groupName" TEXT,
    branch TEXT,
    capacity INTEGER,
    "maxMembers" INTEGER,
    members JSONB,
    instructor TEXT,
    "trainerName" TEXT,
    description TEXT,
    "createdAt" TIMESTAMPTZ
);

-- 6. SCHEDULES
CREATE TABLE schedules (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "groupId" TEXT,
    "groupName" TEXT,
    branch TEXT,
    court TEXT,
    day TEXT,
    "startTime" TEXT,
    "endTime" TEXT,
    instructor TEXT,
    "trainerName" TEXT,
    "createdAt" TIMESTAMPTZ
);

-- 7. ATTENDANCE RECORDS
CREATE TABLE "attendanceRecords" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "memberId" TEXT,
    "groupId" TEXT,
    "scheduleId" TEXT,
    date DATE,
    status TEXT,
    reason TEXT,
    notes TEXT,
    "recordedBy" TEXT,
    "createdAt" TIMESTAMPTZ
);

-- 8. CRM LEADS
CREATE TABLE "crmLeads" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "fullName" TEXT,
    phone TEXT,
    email TEXT,
    source TEXT,
    status TEXT,
    branches JSONB,
    notes TEXT,
    history JSONB,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT,
    "updatedAt" TIMESTAMPTZ,
    "updatedBy" TEXT
);

-- 9. CRM TAGS
CREATE TABLE "crmTags" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    name TEXT,
    category TEXT,
    description TEXT,
    "order" INTEGER,
    "isActive" BOOLEAN,
    "isSystem" BOOLEAN,
    "isAutoGenerated" BOOLEAN,
    "requiresDate" BOOLEAN,
    "createdAt" TIMESTAMPTZ,
    "updatedAt" TIMESTAMPTZ
);

-- 10. WHATSAPP DEVICES
CREATE TABLE "whatsappDevices" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "instanceName" TEXT,
    "phoneNumber" TEXT,
    "apiKey" TEXT,
    "evolutionUrl" TEXT,
    status TEXT,
    "lastUpdated" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT,
    "updatedAt" TIMESTAMPTZ
);

-- 11. WHATSAPP INCOMING CALLS
CREATE TABLE "whatsappIncomingCalls" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "phoneNumber" TEXT,
    "callerName" TEXT,
    "callTime" TIMESTAMPTZ,
    duration INTEGER,
    "isAnswered" BOOLEAN,
    "isDeleted" BOOLEAN,
    "isHidden" BOOLEAN,
    notes TEXT,
    "convertedToLead" BOOLEAN,
    "leadId" TEXT,
    "createdAt" TIMESTAMPTZ
);

-- 12. WHATSAPP INCOMING MESSAGES
CREATE TABLE "whatsappIncomingMessages" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "fromNumber" TEXT,
    "toNumber" TEXT,
    "messageText" TEXT,
    "messageType" TEXT,
    "mediaUrl" TEXT,
    timestamp TIMESTAMPTZ,
    "isRead" BOOLEAN,
    "webhookData" JSONB,
    "createdAt" TIMESTAMPTZ
);

-- 13. WHATSAPP MESSAGES
CREATE TABLE "whatsappMessages" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "toNumber" TEXT,
    "messageText" TEXT,
    "deviceId" TEXT,
    "instanceName" TEXT,
    status TEXT,
    "sentAt" TIMESTAMPTZ,
    "deliveredAt" TIMESTAMPTZ,
    error TEXT,
    "errorMessage" TEXT,
    "createdAt" TIMESTAMPTZ,
    "updatedAt" TIMESTAMPTZ
);

-- 14. SENT MESSAGES
CREATE TABLE "sentMessages" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    phone TEXT,
    recipient TEXT,
    "recipientName" TEXT,
    "recipientPhone" TEXT,
    message TEXT,
    type TEXT,
    "instanceName" TEXT,
    status TEXT,
    success BOOLEAN,
    "sentAt" TIMESTAMPTZ,
    "sentBy" TEXT
);

-- 15. MESSAGE QUEUE
CREATE TABLE "messageQueue" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    phone TEXT,
    message TEXT,
    "deviceId" TEXT,
    status TEXT,
    "scheduledFor" TIMESTAMPTZ,
    error TEXT,
    "failedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ
);

-- 16. SCHEDULED MESSAGES
CREATE TABLE "scheduledMessages" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "phoneNumber" TEXT,
    "recipientName" TEXT,
    "messageText" TEXT,
    "messageType" TEXT,
    "deviceId" TEXT,
    "scheduledTime" TIMESTAMPTZ,
    status TEXT,
    "retryCount" INTEGER,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT
);

-- 17. CAMPAIGNS
CREATE TABLE campaigns (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "campaignName" TEXT,
    "messageText" TEXT,
    "targetAudience" JSONB,
    "recipientCount" INTEGER,
    "sentCount" INTEGER,
    status TEXT,
    "scheduledFor" TIMESTAMPTZ,
    "startedAt" TIMESTAMPTZ,
    "completedAt" TIMESTAMPTZ,
    "createdBy" TEXT,
    "createdAt" TIMESTAMPTZ,
    "updatedAt" TIMESTAMPTZ
);

-- 18. TASKS
CREATE TABLE tasks (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "taskName" TEXT,
    messages TEXT,
    notes TEXT,
    status TEXT,
    "assignedTo" TEXT,
    "completedAt" TIMESTAMPTZ,
    "createdAt" TIMESTAMPTZ
);

-- 19. EXPENSES
CREATE TABLE expenses (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    branch TEXT,
    description TEXT,
    amount DECIMAL(10,2),
    date DATE,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT
);

-- 20. PRODUCTS
CREATE TABLE products (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    branch TEXT,
    name TEXT,
    category TEXT,
    price DECIMAL(10,2),
    stock INTEGER,
    "createdAt" TIMESTAMPTZ,
    "createdBy" TEXT
);

-- 21. WEBHOOKS
CREATE TABLE webhooks (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    url TEXT,
    "eventType" TEXT,
    active BOOLEAN,
    "updatedAt" TIMESTAMPTZ,
    "updatedBy" TEXT
);

-- 22. USER ACTIVITIES
CREATE TABLE "userActivities" (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    activity TEXT,
    branch TEXT,
    "memberId" TEXT,
    "memberName" TEXT,
    phone TEXT,
    "loginType" TEXT,
    timestamp TIMESTAMPTZ,
    "userAgent" TEXT
);

-- 23. HOLIDAYS
CREATE TABLE holidays (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "holidayName" TEXT,
    "startDate" DATE,
    "endDate" DATE,
    description TEXT,
    "createdAt" TIMESTAMPTZ,
    "updatedAt" TIMESTAMPTZ
);

-- 24. BRANCHES
CREATE TABLE branches (
    id TEXT PRIMARY KEY,
    "clubId" TEXT,
    "branchName" TEXT,
    "branchId" TEXT,
    icon TEXT,
    color TEXT,
    courts JSONB,
    "isActive" BOOLEAN,
    iban TEXT,
    "accountHolder" TEXT,
    "bankName" TEXT,
    payment JSONB,
    "paymentInstructions" TEXT,
    "createdAt" TIMESTAMPTZ,
    "updatedAt" TIMESTAMPTZ
);

-- INDEXES (IF NOT EXISTS için önce sil)
DROP INDEX IF EXISTS idx_members_clubId;
DROP INDEX IF EXISTS idx_members_telefon;
DROP INDEX IF EXISTS idx_members_brans;
DROP INDEX IF EXISTS idx_preReg_clubId;
DROP INDEX IF EXISTS idx_schedules_clubId;
DROP INDEX IF EXISTS idx_schedules_groupId;
DROP INDEX IF EXISTS idx_crmLeads_clubId;
DROP INDEX IF EXISTS idx_crmLeads_status;
DROP INDEX IF EXISTS idx_crmLeads_phone;
DROP INDEX IF EXISTS idx_users_clubId;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_groups_clubId;

-- Şimdi yeniden oluştur
CREATE INDEX idx_members_clubId ON members("clubId");
CREATE INDEX idx_members_telefon ON members("Telefon");
CREATE INDEX idx_members_brans ON members("Brans");
CREATE INDEX idx_preReg_clubId ON "preRegistrations"("clubId");
CREATE INDEX idx_schedules_clubId ON schedules("clubId");
CREATE INDEX idx_schedules_groupId ON schedules("groupId");
CREATE INDEX idx_crmLeads_clubId ON "crmLeads"("clubId");
CREATE INDEX idx_crmLeads_status ON "crmLeads"(status);
CREATE INDEX idx_crmLeads_phone ON "crmLeads"(phone);
CREATE INDEX idx_users_clubId ON users("clubId");
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_groups_clubId ON groups("clubId");
CREATE INDEX idx_whatsappCalls_clubId_callTime ON "whatsappIncomingCalls"("clubId", "callTime" DESC);
CREATE INDEX idx_crmTags_clubId ON "crmTags"("clubId");

-- RLS KAPATILDI (import için)
ALTER TABLE clubs DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE members DISABLE ROW LEVEL SECURITY;
ALTER TABLE "preRegistrations" DISABLE ROW LEVEL SECURITY;
ALTER TABLE groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE "attendanceRecords" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "crmLeads" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "crmTags" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "whatsappDevices" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "whatsappIncomingCalls" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "whatsappIncomingMessages" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "whatsappMessages" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "sentMessages" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "messageQueue" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "scheduledMessages" DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE webhooks DISABLE ROW LEVEL SECURITY;
ALTER TABLE "userActivities" DISABLE ROW LEVEL SECURITY;
ALTER TABLE holidays DISABLE ROW LEVEL SECURITY;
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;

